version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    env_file:
      - .env  # dynamic env file selection
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${API_URL}
    env_file:
      - .env
    restart: always
